env: "dev"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
token:
  secret_key: "topsecret"
  accessTtl: 15m
  refreshTtl: 201600m
postgres:
  host: "localhost"
  port: "5436"
  user: "postgres"
  password: "qwerty"
  db_name: "postgres"